#!/usr/bin/env bash

rm -rf ~/.config/nvim
ln -s $(pwd) ~/.config/nvim
rm -rf ~/.config/tmux
rm -rf ~/.tmux
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
ln -s $(pwd)/tmux ~/.config/tmux
